// Generated by CoffeeScript 1.6.1
var app, io, port, server;

app = require("express")();

server = require("http").createServer(app);

port = Number(process.argv[2]);

/* HTTP P2P Server
*/


app.get("/", function(req, res) {
  return res.send("<body>\n  <textarea id=\"chat\" cols=\"40\" rows=\"5\"></textarea>\n  <div id=\"info\"></div>\n  <script src=\"/socket.io/socket.io.js\"></script>\n  <script>\n    var chat = document.getElementById(\"chat\"), \n      socket = io.connect(\"http://localhost:" + port + "\", {\n          \"reconnect\": true,\n          \"reconnection delay\": 500,\n          \"max reconnection attempts\": 99999\n        }),\n      myself_emitted = false,\n      info = document.getElementById(\"info\");\n\n    socket.on('connect', function() {\n      info.innerHTML = \"connected to " + port + "\";\n    });\n    socket.on('disconnect', function() {\n      info.innerHTML = \"disconnected\";\n    });\n\n    socket.on('chat', function (data) {\n      if (!myself_emitted) {\n        chat.value = data;\n      } \n      myself_emitted = false;\n    });\n\n    chat.addEventListener( \"keyup\",\n      function(e) {\n        myself_emitted = true;\n        socket.emit(\"chat\", chat.value)\n      }\n    );\n  </script>\n</body>");
});

server.listen(port);

console.log("Listening on port " + port);

/* Socket.io
*/


io = require("socket.io").listen(server);

io.set("log level", 0);

io.sockets.on("connection", function(socket) {
  console.log("Connection");
  return socket.on("chat", function(v) {
    return io.of('').emit("chat", v);
  });
});
